package com.viciy.downloadmanager.greendao;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;


// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig installTaskDaoConfig;

    private final InstallTaskDao installTaskDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        installTaskDaoConfig = daoConfigMap.get(InstallTaskDao.class).clone();
        installTaskDaoConfig.initIdentityScope(type);

        installTaskDao = new InstallTaskDao(installTaskDaoConfig, this);

        registerDao(InstallTask.class, installTaskDao);
    }
    
    public void clear() {
        installTaskDaoConfig.getIdentityScope().clear();
    }

    public InstallTaskDao getInstallTaskDao() {
        return installTaskDao;
    }

}
