package com.viciy.downloadmanager.greendao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table INSTALL_TASK.
 */
public class InstallTask {

    private Long id;
    /** Not-null value. */
    private String apkUrl;
    private String downloadId;

    public InstallTask() {
    }

    public InstallTask(Long id) {
        this.id = id;
    }

    public InstallTask(Long id, String downloadId, String apkUrl) {
        this.id = id;
        this.apkUrl = apkUrl;
        this.downloadId = downloadId;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    /** Not-null value. */
    public String getApkUrl() {
        return apkUrl;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setApkUrl(String apkUrl) {
        this.apkUrl = apkUrl;
    }

    public String getDownloadId() {
        return downloadId;
    }

    public void setDownloadId(String downloadId) {
        this.downloadId = downloadId;
    }

}


